# ###################################################
#         Lyttle Chunk Loader - chunks.yml          #
# ###################################################
# Main configuration file for the Lyttle Chunk Loader plugin.
# This file contains settings that control the behavior of the plugin.
# ###################################################


# ⚠️ Do not change this value.
config_version: 0